# Generated by Django 4.2.4 on 2023-10-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockproduct',
            old_name='product',
            new_name='products',
        ),
    ]
