name: Testing

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-22.04
    env:
      PASSWORD: ${{ secrets.DB_PASSWORD }}
    services:
      postgresql:
        image: postgres:12
        env:
          POSTGRES_DB: netology_stocks_products
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ env.PASSWORD }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timout 5s
          --health-retries 5
    steps:
      - name: проверка наличия изменений
        uses: actions/checkout@v3

      - name: Установка python и доп.библиотек
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Зависимости проекта
        run: pip install -r requirements.txt

      - name: Линтинг
        run: flake8 logistic --exclude logistic/migrations

      - name: Тестирование
        run: python manage.py test

      - name: Деплой